# HTTP
quarkus.http.port=8081

# === Database ===
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=root
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/insurance_db
quarkus.hibernate-orm.database.generation=update

# === Matikan semua DevServices (termasuk Kafka) ===
quarkus.devservices.enabled=false
quarkus.kafka.devservices.enabled=false

# === Kafka pakai instance dari docker-compose ===
# shared bootstrap untuk semua channel smallrye-kafka
mp.messaging.connector.smallrye-kafka.bootstrap.servers=localhost:9092
# (opsional tapi aman juga)
kafka.bootstrap.servers=localhost:9092

# === Channel Kafka untuk registration-service ===
mp.messaging.outgoing.registration-out.connector=smallrye-kafka
mp.messaging.outgoing.registration-out.topic=registration-email-topic
