# HTTP
quarkus.http.port=8082

# === Database ===
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=root
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/insurance_db
quarkus.hibernate-orm.database.generation=update

# === Matikan DevServices ===
quarkus.devservices.enabled=false
quarkus.kafka.devservices.enabled=false

# === Kafka external ===
mp.messaging.connector.smallrye-kafka.bootstrap.servers=localhost:9092
kafka.bootstrap.servers=localhost:9092

# === Channel Kafka untuk email-service (consumer) ===
mp.messaging.incoming.registration-in.connector=smallrye-kafka
mp.messaging.incoming.registration-in.topic=registration-email-topic
mp.messaging.incoming.registration-in.group.id=email-service-group
mp.messaging.incoming.registration-in.auto.offset.reset=earliest
